/* 
 * URL Validation
 *
 * The URL Validation service is used to confirm that a particular URL, or multiple URLs, is valid and safe to use. For example, if you are designing a communication for customers and want to include a URL, you can check that the URL goes to a valid, active website before sending the communication.   The service validates web page addresses that use the HTTP and HTTPS application protocols. It does not process web addresses that are in the IPv4 and IPv6 address format.	## Key functionality:	* Validates URLs to a level specified and configured by the user.  * Validates the existence of domains and conformity to patterns.  * Checks whether a web server is responsive when queried for the URL.	* Handles complexities, such as URL redirection.  * Adds missing URL pieces, such as scheme, and removes noise from the input.	* Provides codes to warn the user of authentication requirements, browser-specific URL length restrictions, and so forth. 
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServices.Model.Url
{
	/// <summary>
	/// UrlValidationResponse
	/// </summary>
	[DataContract]
	public partial class UrlValidationResponse : IEquatable<UrlValidationResponse>, IValidatableObject
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="UrlValidationResponse" /> class.
		/// </summary>
		/// <param name="Records">Records.</param>
		public UrlValidationResponse(List<UrlValidationResponseRecord> Records = default(List<UrlValidationResponseRecord>))
		{
			this.Records = Records;
		}
		
		/// <summary>
		/// Gets or Sets Records
		/// </summary>
		[DataMember(Name="records", EmitDefaultValue=false)]
		public List<UrlValidationResponseRecord> Records { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString()
		{
			var sb = new StringBuilder();
			sb.Append("class UrlValidationResponse {\n");
			sb.Append("  Records: ").Append(Records).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}
  
		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson()
		{
			return JsonConvert.SerializeObject(this, Formatting.Indented);
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="input">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object input)
		{
			return this.Equals(input as UrlValidationResponse);
		}

		/// <summary>
		/// Returns true if UrlValidationResponse instances are equal
		/// </summary>
		/// <param name="input">Instance of UrlValidationResponse to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(UrlValidationResponse input)
		{
			if (input == null)
				return false;

			return 
				(
					this.Records == input.Records ||
					this.Records != null &&
					this.Records.SequenceEqual(input.Records)
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
		{
			unchecked // Overflow is fine, just wrap
			{
				int hashCode = 41;
				if (this.Records != null)
					hashCode = hashCode * 59 + this.Records.GetHashCode();
				return hashCode;
			}
		}

		/// <summary>
		/// To validate all properties of the instance
		/// </summary>
		/// <param name="validationContext">Validation context</param>
		/// <returns>Validation Result</returns>
		IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
		{
			yield break;
		}
	}

}
