/* 
 * User Management
 *
 * Provides an API to:   * Enumerate the user base   * Create new users   * Gather specific user's information   * Change a user's information  User information include things like:   * Whether or not the user account is `enabled` or not   * Username/password credentials as well as API keys   * Contact information such as `first_name`, `last_name`, `organization` and `email_address`   * Group membership - membership of a `group` is used to grant access to services and features   * Tenant membership - membership of a `tenant` is used to assign users specific `roles` in a organization   * Additional details - each user may have a collection of custom key-value pairs  For details about authentication, refer to the [authentication specification](/oauth/swagger.json).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServices.Model.User
{
    /// <summary>
    /// ServiceAccessDescriptorListing
    /// </summary>
    [DataContract]
    public partial class ServiceAccessDescriptorListing :  IEquatable<ServiceAccessDescriptorListing>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceAccessDescriptorListing" /> class.
        /// </summary>
        /// <param name="ServiceAccessDescriptors">A list of service access descriptors for the tenant..</param>
        public ServiceAccessDescriptorListing(List<ServiceAccessDescriptor> ServiceAccessDescriptors = default(List<ServiceAccessDescriptor>))
        {
            this.ServiceAccessDescriptors = ServiceAccessDescriptors;
        }
        
        /// <summary>
        /// A list of service access descriptors for the tenant.
        /// </summary>
        /// <value>A list of service access descriptors for the tenant.</value>
        [DataMember(Name="service_access_descriptors", EmitDefaultValue=false)]
        public List<ServiceAccessDescriptor> ServiceAccessDescriptors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceAccessDescriptorListing {\n");
            sb.Append("  ServiceAccessDescriptors: ").Append(ServiceAccessDescriptors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceAccessDescriptorListing);
        }

        /// <summary>
        /// Returns true if ServiceAccessDescriptorListing instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceAccessDescriptorListing to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceAccessDescriptorListing input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServiceAccessDescriptors == input.ServiceAccessDescriptors ||
                    this.ServiceAccessDescriptors != null &&
                    this.ServiceAccessDescriptors.SequenceEqual(input.ServiceAccessDescriptors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServiceAccessDescriptors != null)
                    hashCode = hashCode * 59 + this.ServiceAccessDescriptors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
