/* 
 * Sentiment Analysis
 *
 * The Sentiment Analysis service offers insight into what customers are saying and feeling about your brand or product. Taking advantage of machine learning, the service can help you monitor customer perception and help influence the direction of your marketing and customer experience operations.	The service can analyze data from a variety of data sources, including Twitter and text contained in .csv files, say from customer support survey responses, and presents multiple visualizations of the results. You can review trends over time, easily learn what's hot and what's not based on the content of your data, and if you tap into the data in your Twitter feed, get a list of the topics that are the hottest and the messages that are the most intense.  Key functionality: * Steps you through setup with an easy to understand wizard. * Tracks sentiment per day/hour per topic. * Captures the most intense messages in periods ranging from seven to 30 days. * Provides sentiment visualizations that capture what topics your customers are discussing. 
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServices.Model.SentimentAnalysis
{
	/// <summary>
	/// Uses a table ID from the ETL service.  Required: The data has to have a &#39;text&#39; column header.  Optional: &#39;date, &#39;language&#39;, and &#39;id&#39; column headers are also supported.  &#39;date&#39; has to be a valid date time string.  &#39;language&#39; has to be in 2-letter ISO 639-1 format. Table rows that have languages that are not supported are skipped.
	/// </summary>
	[DataContract]
	public partial class FileDataConfiguration : IEquatable<FileDataConfiguration>, IValidatableObject
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="FileDataConfiguration" /> class.
		/// </summary>
		/// <param name="FileId">Table ID from the ETL service..</param>
		public FileDataConfiguration(string FileId = default(string))
		{
			this.FileId = FileId;
		}
		
		/// <summary>
		/// Table ID from the ETL service.
		/// </summary>
		/// <value>Table ID from the ETL service.</value>
		[DataMember(Name="file_id", EmitDefaultValue=false)]
		public string FileId { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString()
		{
			var sb = new StringBuilder();
			sb.Append("class FileDataConfiguration {\n");
			sb.Append("  FileId: ").Append(FileId).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}
  
		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson()
		{
			return JsonConvert.SerializeObject(this, Formatting.Indented);
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="input">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object input)
		{
			return this.Equals(input as FileDataConfiguration);
		}

		/// <summary>
		/// Returns true if FileDataConfiguration instances are equal
		/// </summary>
		/// <param name="input">Instance of FileDataConfiguration to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(FileDataConfiguration input)
		{
			if (input == null)
				return false;

			return 
				(
					this.FileId == input.FileId ||
					(this.FileId != null &&
					this.FileId.Equals(input.FileId))
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
		{
			unchecked // Overflow is fine, just wrap
			{
				int hashCode = 41;
				if (this.FileId != null)
					hashCode = hashCode * 59 + this.FileId.GetHashCode();
				return hashCode;
			}
		}

		/// <summary>
		/// To validate all properties of the instance
		/// </summary>
		/// <param name="validationContext">Validation context</param>
		/// <returns>Validation Result</returns>
		IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
		{
			yield break;
		}
	}

}
