/* 
 * Sentiment Analysis
 *
 * The Sentiment Analysis service offers insight into what customers are saying and feeling about your brand or product. Taking advantage of machine learning, the service can help you monitor customer perception and help influence the direction of your marketing and customer experience operations.	The service can analyze data from a variety of data sources, including Twitter and text contained in .csv files, say from customer support survey responses, and presents multiple visualizations of the results. You can review trends over time, easily learn what's hot and what's not based on the content of your data, and if you tap into the data in your Twitter feed, get a list of the topics that are the hottest and the messages that are the most intense.  Key functionality: * Steps you through setup with an easy to understand wizard. * Tracks sentiment per day/hour per topic. * Captures the most intense messages in periods ranging from seven to 30 days. * Provides sentiment visualizations that capture what topics your customers are discussing. 
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServices.Model.SentimentAnalysis
{
	/// <summary>
	/// TransactionalArtifactOutcome
	/// </summary>
	[DataContract]
	public partial class TransactionalArtifactOutcome : IEquatable<TransactionalArtifactOutcome>, IValidatableObject
	{
		/// <summary>
		/// Sentiment analysis outcome.
		/// </summary>
		/// <value>Sentiment analysis outcome.</value>
		[JsonConverter(typeof(StringEnumConverter))]
		public enum CategoryEnum
		{
			
			/// <summary>
			/// Enum Analyzed for value: Analyzed
			/// </summary>
			[EnumMember(Value = "Analyzed")]
			Analyzed = 1,
			
			/// <summary>
			/// Enum Skipped for value: Skipped
			/// </summary>
			[EnumMember(Value = "Skipped")]
			Skipped = 2
		}

		/// <summary>
		/// Sentiment analysis outcome.
		/// </summary>
		/// <value>Sentiment analysis outcome.</value>
		[DataMember(Name="category", EmitDefaultValue=false)]
		public CategoryEnum Category { get; set; }
		/// <summary>
		/// Initializes a new instance of the <see cref="TransactionalArtifactOutcome" /> class.
		/// </summary>
		[JsonConstructorAttribute]
		protected TransactionalArtifactOutcome() { }
		/// <summary>
		/// Initializes a new instance of the <see cref="TransactionalArtifactOutcome" /> class.
		/// </summary>
		/// <param name="Category">Sentiment analysis outcome. (required).</param>
		/// <param name="Codes">Codes.</param>
		public TransactionalArtifactOutcome(CategoryEnum Category = default(CategoryEnum), Object Codes = default(Object))
		{
			// to ensure "Category" is required (not null)
			if (Category == null)
			{
				throw new InvalidDataException("Category is a required property for TransactionalArtifactOutcome and cannot be null");
			}
			else
			{
				this.Category = Category;
			}
			this.Codes = Codes;
		}
		

		/// <summary>
		/// Gets or Sets Codes
		/// </summary>
		[DataMember(Name="codes", EmitDefaultValue=false)]
		public Object Codes { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString()
		{
			var sb = new StringBuilder();
			sb.Append("class TransactionalArtifactOutcome {\n");
			sb.Append("  Category: ").Append(Category).Append("\n");
			sb.Append("  Codes: ").Append(Codes).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}
  
		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson()
		{
			return JsonConvert.SerializeObject(this, Formatting.Indented);
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="input">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object input)
		{
			return this.Equals(input as TransactionalArtifactOutcome);
		}

		/// <summary>
		/// Returns true if TransactionalArtifactOutcome instances are equal
		/// </summary>
		/// <param name="input">Instance of TransactionalArtifactOutcome to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(TransactionalArtifactOutcome input)
		{
			if (input == null)
				return false;

			return 
				(
					this.Category == input.Category ||
					(this.Category != null &&
					this.Category.Equals(input.Category))
				) && 
				(
					this.Codes == input.Codes ||
					(this.Codes != null &&
					this.Codes.Equals(input.Codes))
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
		{
			unchecked // Overflow is fine, just wrap
			{
				int hashCode = 41;
				if (this.Category != null)
					hashCode = hashCode * 59 + this.Category.GetHashCode();
				if (this.Codes != null)
					hashCode = hashCode * 59 + this.Codes.GetHashCode();
				return hashCode;
			}
		}

		/// <summary>
		/// To validate all properties of the instance
		/// </summary>
		/// <param name="validationContext">Validation context</param>
		/// <returns>Validation Result</returns>
		IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
		{
			yield break;
		}
	}

}
