/* 
 * Walk Sequence
 *
 * Performs USPS CASS processing and appends USPS Walk Sequence numbers to mail pieces. Properly walk sequenced mailings may qualify for USPS mailing discounts.  ## Job execution  The general flow to execute a batch job is to:  1. Create a job, specifying configuration properties, upload and download schema (input fields and output fields). Job configuration cannot be changed after creation.  2. Upload records to process via one or more calls to the `/jobs/{job_id}/records` endpoint. Records are uploaded in blocks. The records are stored on the server for processing.  3. Initiate processing by calling the `/jobs/{job_id}/_run` endpoint. 4. Wait for the job status to enter `SUCCESS` or `FAILED`. 5. Download the records. 6. Delete job when you are done with it via a `DELETE` on the `/jobs/{job_id}` endpoint, removing input and output records.  ## Records  Records must be uploaded completely prior to running the service. Records are categorized as `input` or `output`. The schema (fields and order) of the records are defined via the job creation call.  ## Pagination Records for a job are broken into pages (`page_id`) for retrieval. The collection of record page ids are available via the `/jobs/{job_id}/records/pages` endpoint. Retrieve this collection as a precursor to downloading records. Each record page can then be retrieved by the client. Page IDs are immutable and can be retrieved in parallel. Record pages may also be retrieved multiple times if needed. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServies.Model.WalkSequence
{
    /// <summary>
    /// Defines WalkSequenceOutputField
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WalkSequenceOutputField
    {
        
        id = 1,
        
        abbreviated_city = 2,
        
        address_block = 3,
        
        address_line_1 = 4,
        
        address_line_2 = 5,
        
        address_type = 6,
        
        business = 7,
        
        carrier_route = 8,
        
        city = 9,
        
        congressional_district = 10,
        
        country = 11,
        
        county = 12,
        
        county_code = 13,
        
        delivery_point = 14,
        
        dpv_coded = 15,
        
        dpv_footnote = 16,
        
        dpv_indicator = 17,
        
        elot = 18,
        
        extra_address_information = 19,
        
        first_name = 20,
        
        full_name = 21,
        
        is_cmra = 22,
        
        is_ews_match = 23,
        
        is_no_stat = 24,
        
        is_pbsa = 25,
        
        is_vacant = 26,
        
        is_residence = 27,
        
        is_educational_institute = 28,
        
        is_seasonally_occupied = 29,
        
        lacs_coded = 30,
        
        lacs_link_footnote = 31,
        
        lacs_link_indicator = 32,
        
        city_state_zip = 33,
        
        last_name = 34,
        
        matched_to_default = 35,
        
        middle_name = 36,
        
        name_suffix = 37,
        
        post_directional = 38,
        
        pre_directional = 39,
        
        primary_address_line = 40,
        
        primary_number = 41,
        
        private_mailbox = 42,
        
        secondary_address_line = 43,
        
        state = 44,
        
        street_name = 45,
        
        street_suffix = 46,
        
        suite_link_footnote = 47,
        
        unit_designator = 48,
        
        unit_number = 49,
        
        urbanization = 50,
        
        uscorrection_description = 51,
        
        uscorrection_footnote = 52,
        
        walk_sequence_footnote = 53,
        
        walk_sequence_number = 54,
        
        zip_code = 55
    }
    
}
