/* 
 * US Move Update
 *
 * The US Move Update service offers the ability to update addresses of persons and organizations who have moved within the United States.  ## Job execution  The general flow to execute a batch job is to:  1. Create a job, specifying its configuration properties, and upload and download schema (input fields and output fields). You cannot change the job's configuration after creation.  2. Upload records to process via one or more calls to the `/jobs/{job_id}/records` endpoint. Records are uploaded in blocks. The records are stored on the server for processing.  3. Initiate processing by calling the `/jobs/{job_id}/_run` endpoint. 4. Wait for the job status to be updated to `SUCCESS` or `FAILED`. 5. Download the records. 6. Delete job when you are done by requesting a `DELETE` on the `/jobs/{job_id}` endpoint, which removes both input and output records.  ## Records  The upload of records must be complete prior to running the service. Records are categorized as `input` or `output`. The schema (fields and order) of the records is defined via the job creation call.  ## Pagination Records for a job are broken into pages (`page_id`) for retrieval. The collection of record page IDs is available via the `/jobs/{job_id}/records/pages` endpoint. Retrieve this collection as a precursor to downloading records. Each record page can then be retrieved by the client. Page IDs are immutable and can be retrieved in parallel. Record pages may also be retrieved multiple times if needed. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Quadient.DataServices.Model.Client.SwaggerDateConverter;

namespace Quadient.DataServices.Model.UsBatch
{
    /// <summary>
    /// &#x60;No change&#x60; - No move was found for the address. &#x60;Moved away&#x60; - A move was detected, but no new address was available. &#x60;New address&#x60; - A move was found and returned. 
    /// </summary>
    /// <value>&#x60;No change&#x60; - No move was found for the address. &#x60;Moved away&#x60; - A move was detected, but no new address was available. &#x60;New address&#x60; - A move was found and returned. </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MoveUpdateOutcomeCategory
    {
        
        /// <summary>
        /// Enum Nochange for value: No_change
        /// </summary>
        [EnumMember(Value = "No_change")]
        Nochange = 1,
        
        /// <summary>
        /// Enum Movedaway for value: Moved_away
        /// </summary>
        [EnumMember(Value = "Moved_away")]
        Movedaway = 2,
        
        /// <summary>
        /// Enum Newaddress for value: New_address
        /// </summary>
        [EnumMember(Value = "New_address")]
        Newaddress = 3
    }
}
